"""Lightweight, easy-to-use, flexible composite data structures."""

from __future__ import annotations

__version__ = "0.2.1"

__author__: str = "Corey Rayburn Yung"

from .applications import System
from .base import (
    Composite,
    Edge,
    Forms,
    Graph,
    Node,
    Structural,
    classify,
    transform,
)
from .check import (
    add_checker,
    is_adjacency,
    is_composite,
    is_edge,
    is_edges,
    is_graph,
    is_matrix,
    is_node,
    is_nodes,
    is_parallel,
    is_serial,
)
from .composites import Parallel, Serial
from .export import to_dot, to_mermaid
from .graphs import Adjacency, Edges, Matrix
from .options import get_base, set_base
from .report import (
    get_endpoints,
    get_endpoints_adjacency,
    get_endpoints_edges,
    get_endpoints_matrix,
    get_endpoints_parallel,
    get_endpoints_serial,
    get_roots,
    get_roots_adjacency,
    get_roots_edges,
    get_roots_matrix,
    get_roots_parallel,
    get_roots_serial,
)
from .traits import Directed, Exportable, Fungible, Labeled, Storage, Weighted
from .traverse import (
    walk,
    walk_adjacency,
    walk_edges,
    walk_matrix,
    walk_parallel,
    walk_serial,
)
from .workshop import (
    add_transformer,
    adjacency_to_edges,
    adjacency_to_matrix,
    adjacency_to_parallel,
    adjacency_to_serial,
    edges_to_adjacency,
    edges_to_matrix,
    edges_to_parallel,
    edges_to_serial,
    matrix_to_adjacency,
    matrix_to_edges,
    matrix_to_parallel,
    matrix_to_serial,
    parallel_to_adjacency,
    parallel_to_edges,
    parallel_to_matrix,
    parallel_to_serial,
    serial_to_adjacency,
    serial_to_edges,
    serial_to_matrix,
    serial_to_parallel,
)

__all__: list[str] = [
    "Adjacency",
    "Composite",
    "Directed",
    "Edge",
    "Edges",
    "Exportable",
    "Forms",
    "Fungible",
    "Graph",
    "Labeled",
    "Matrix",
    "Node",
    "Parallel",
    "Serial",
    "Storage",
    "Structural",
    "System",
    "Weighted",
    "add_checker",
    "add_transformer",
    "adjacency_to_edges",
    "adjacency_to_matrix",
    "adjacency_to_parallel",
    "adjacency_to_serial",
    "classify",
    "edges_to_adjacency",
    "edges_to_matrix",
    "edges_to_parallel",
    "edges_to_serial",
    "get_base",
    "get_endpoints",
    "get_endpoints_adjacency",
    "get_endpoints_edges",
    "get_endpoints_matrix",
    "get_endpoints_parallel",
    "get_endpoints_serial",
    "get_roots",
    "get_roots_adjacency",
    "get_roots_edges",
    "get_roots_matrix",
    "get_roots_parallel",
    "get_roots_serial",
    "is_adjacency",
    "is_composite",
    "is_edge",
    "is_edges",
    "is_graph",
    "is_matrix",
    "is_node",
    "is_nodes",
    "is_parallel",
    "is_serial",
    "matrix_to_adjacency",
    "matrix_to_edges",
    "matrix_to_parallel",
    "matrix_to_serial",
    "parallel_to_adjacency",
    "parallel_to_edges",
    "parallel_to_matrix",
    "parallel_to_serial",
    "serial_to_adjacency",
    "serial_to_edges",
    "serial_to_matrix",
    "serial_to_parallel",
    "set_base",
    "to_dot",
    "to_mermaid",
    "transform",
    "walk",
    "walk_adjacency",
    "walk_edges",
    "walk_matrix",
    "walk_parallel",
    "walk_serial",
]
